In [6]:
%matplotlib inline
import pandas as pd
import numpy as np
import glob

In [49]:
df_in = pd.read_csv('../final_data_files/uncrowded_photometry_bv.csv')
df_new = pd.DataFrame(data=np.zeros((1,17)), columns=df_in.columns)
print df_new

def get_data(line):
    mag = line.split('> = ')[1].split(' ')[0]
    merr = line.split('dev = ')[1].split(' ')[0]
    if mag == 'nan':
        mag = np.nan
    else:
        mag = float(mag)
    if merr == 'nan':
        merr = np.nan
    else:
        merr == float(merr)
    return mag, merr

kaluz = pd.read_csv('../Kaluzny2004rrl.txt', delim_whitespace=True)

def parse_gloess_output(gloessfile, df_new):
    starid = int(gloessfile.split('/')[1].split('.')[0])
    nanarray = np.zeros((1,17))
    nanarray[nanarray == 0] = np.nan
    new_row = pd.DataFrame(data = nanarray, columns=df_in.columns)
    new_row.id = starid
    new_row.per = kaluz.per[kaluz.id == starid].values[0]
    new_row.type = kaluz.type[kaluz.id == starid].values[0]
    f = open(gloessfile)
    for line in f:
        mag, merr = get_data(line)
        if line.startswith('<B'):
            new_row.mag_b = mag
            new_row.merr_b = merr
        if line.startswith('<V'):
            new_row.mag_v = mag
            new_row.merr_v = merr
        if line.startswith('<J'):
            new_row.mag_j = mag
            new_row.merr_j = merr
        if line.startswith('<H'):
            new_row.mag_h = mag
            new_row.merr_h = merr
        if line.startswith('<K'):
            new_row.mag_k = mag
            new_row.merr_k = merr
        if line.startswith('<[3'):
            new_row.mag_3 = mag
            new_row.merr_3 = merr
        if line.startswith('<[4'):
            new_row.mag_4 = mag
            new_row.merr_4 = merr
    f.close()
    df_new = pd.concat([df_new, new_row], ignore_index=True)
    return df_new

   id  mag_j  merr_j  type  per  mag_h  merr_h  mag_k  merr_k  mag_3  merr_3  \
0   0      0       0     0    0      0       0      0       0      0       0

   mag_4  merr_4  mag_v  merr_v  mag_b  merr_b
0      0       0      0       0      0       0

[1 rows x 17 columns]

In [51]:
for i in glob.glob('multiband_output/*.glo_avs'):
    df_new = parse_gloess_output(i, df_new)

In [60]:
df_new = df_new.drop(df_new[df_new.id == 0].index).sort(columns='id')

In [62]:
df_new.to_csv('../final_data_files/photometry_gloess.csv', index=False)

In [76]:
df_new.merge(df_in, how='left', on=[i for i in df_new.columns])

,id,mag_j,merr_j,type,per,mag_h,merr_h,mag_k,merr_k,mag_3,merr_3,mag_4,merr_4,mag_v,merr_v,mag_b,merr_b
0,3,13.209,0.130,0,0.841258,12.992,0.065,12.865,0.104,12.849,0.085,12.713,0.070,14.413,0.231,NaN,NaN
1,4,13.469,0.110,0,0.627320,13.260,0.137,13.161,0.060,13.023,0.090,13.012,0.098,14.492,0.300,14.974,0.450
2,5,13.788,0.173,0,0.515274,13.632,0.279,13.520,0.128,13.383,0.074,13.333,0.067,14.783,0.291,15.300,0.443
3,7,13.324,0.115,0,0.713000,13.060,0.112,12.987,0.096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8,13.634,0.166,0,0.521329,13.353,0.142,13.296,0.108,NaN,NaN,NaN,NaN,14.746,0.377,15.177,0.514
5,9,13.742,0.080,0,0.523480,13.505,0.088,13.448,0.048,13.310,0.027,13.270,0.055,14.796,0.312,15.327,0.468
6,10,13.581,0.049,1,0.374976,13.398,0.052,13.344,0.031,13.344,0.027,13.167,0.037,14.491,0.130,14.917,0.201
7,11,13.505,0.087,0,0.564789,13.309,0.117,13.223,0.081,NaN,NaN,NaN,NaN,14.552,0.244,14.939,0.332
8,12,13.606,0.063,1,0.386769,13.400,0.116,13.311,0.049,13.169,0.026,13.452,0.133,14.532,0.153,14.949,0.216
9,13,13.343,0.132,0,0.669039,13.090,0.100,13.039,0.081,12.903,0.071,12.843,0.083,14.496,0.282,15.015,0.405
10,14,13.612,0.065,1,0.377114,13.334,0.032,13.354,0.042,NaN,NaN,NaN,NaN,14.527,0.168,14.915,0.240
11,15,13.234,0.100,0,0.810642,12.961,0.115,12.917,0.083,NaN,NaN,NaN,NaN,14.416,0.209,14.965,0.320
12,16,13.678,0.065,1,0.330202,13.505,0.061,13.441,0.044,NaN,NaN,NaN,NaN,14.577,0.181,14.943,0.254
13,18,13.368,0.100,0,0.621689,13.164,0.090,13.116,0.075,NaN,NaN,NaN,NaN,14.611,0.334,15.023,0.454
14,19,13.886,0.049,1,0.299551,13.730,0.040,13.642,0.030,13.776,0.049,14.269,0.148,14.841,0.164,15.205,0.229
15,20,13.438,0.115,0,0.615559,13.229,0.062,13.197,0.121,13.088,0.089,12.962,0.086,14.620,0.324,15.081,0.427
16,21,13.577,0.072,1,0.380812,13.413,0.051,13.375,0.063,13.301,0.039,13.198,0.018,14.366,0.156,NaN,NaN
17,22,13.557,0.062,1,0.396055,13.384,0.061,13.286,0.041,NaN,NaN,NaN,NaN,14.552,0.123,14.949,0.215
18,23,13.801,0.199,0,0.510870,13.748,0.313,13.498,0.154,NaN,NaN,NaN,NaN,14.907,0.296,15.381,0.438
19,24,13.420,0.072,1,0.462278,13.198,0.047,13.127,0.055,NaN,NaN,NaN,NaN,14.486,0.138,14.896,0.182
20,25,13.520,0.149,0,0.588364,13.296,0.097,13.202,0.132,14.186,0.019,13.187,0.080,14.519,0.297,14.997,0.434
21,26,13.263,0.103,0,0.784720,13.008,0.065,12.921,0.077,NaN,NaN,NaN,NaN,14.515,0.180,15.073,0.262
22,27,13.481,0.083,0,0.615680,13.149,0.073,13.153,0.075,NaN,NaN,NaN,NaN,14.769,0.178,15.292,0.260
23,30,13.515,0.036,1,0.404410,13.309,0.044,13.264,0.036,13.187,0.029,13.061,0.028,14.489,0.124,14.830,0.176
24,32,13.515,0.144,0,0.620373,13.335,0.172,13.152,0.105,NaN,NaN,NaN,NaN,14.574,0.324,15.025,0.443
25,33,13.389,0.109,0,0.602324,13.139,0.076,13.173,0.164,NaN,NaN,NaN,NaN,14.598,0.336,14.976,0.459
26,34,13.278,0.055,0,0.733967,13.013,0.009,12.967,0.087,NaN,NaN,NaN,NaN,14.503,0.231,15.037,0.354
27,35,13.606,0.060,1,0.386841,13.478,0.146,13.343,0.064,NaN,NaN,NaN,NaN,14.574,0.161,14.920,0.232
28,36,13.537,0.055,1,0.379846,13.358,0.056,13.293,0.053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,38,13.231,0.065,0,0.779061,12.955,0.061,12.813,0.035,NaN,NaN,NaN,NaN,14.493,0.181,15.043,0.273
30,39,13.568,0.056,1,0.393374,13.425,0.075,13.311,0.038,NaN,NaN,NaN,NaN,14.580,0.167,14.949,0.239
31,40,13.436,0.155,0,0.634072,13.204,0.106,13.151,0.070,13.041,0.096,13.385,0.103,14.566,0.319,15.046,0.438
32,41,13.108,0.100,0,0.662942,12.515,0.092,12.505,0.079,NaN,NaN,NaN,NaN,14.571,0.282,15.044,0.371
33,44,13.655,0.107,0,0.567545,13.405,0.099,13.354,0.075,14.677,0.061,13.147,0.097,14.769,0.279,15.293,0.408
34,45,13.453,0.145,0,0.589116,13.177,0.118,13.141,0.126,NaN,NaN,NaN,NaN,14.569,0.301,15.102,0.495
35,46,13.340,0.096,0,0.686971,13.031,0.066,12.999,0.115,NaN,NaN,NaN,NaN,14.532,0.265,15.030,0.385
36,47,13.363,0.049,1,0.485303,13.190,0.069,13.144,0.018,13.107,0.034,13.066,0.034,14.353,0.138,NaN,NaN
37,49,13.515,0.116,0,0.604627,13.175,0.100,13.183,0.095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,50,13.622,0.080,1,0.386172,13.383,0.070,13.349,0.064,NaN,NaN,NaN,NaN,14.644,0.164,15.025,0.240
39,51,13.617,0.136,0,0.574152,13.377,0.090,13.292,0.118,NaN,NaN,NaN,NaN,14.612,0.344,15.098,0.494
40,52,12.907,0.100,0,0.660386,12.726,0.120,12.643,0.081,NaN,NaN,NaN,NaN,13.773,0.151,14.135,0.202
41,54,13.242,0.097,0,0.772915,12.936,0.123,12.907,0.070,NaN,NaN,NaN,NaN,14.436,0.196,14.953,0.292
42,56,13.676,0.146,0,0.568023,13.361,0.123,13.352,0.103,NaN,NaN,NaN,NaN,14.786,0.279,NaN,NaN
43,57,13.215,0.074,0,0.794402,12.941,0.090,12.864,0.057,NaN,NaN,NaN,NaN,14.485,0.177,15.011,0.231
44,58,13.630,0.017,1,0.369880,13.475,0.031,13.418,0.041,13.346,0.016,13.303,0.011,14.478,0.095,14.797,0.136
45,59,13.655,0.127,0,0.518506,13.418,0.059,13.355,0.086,13.250,0.062,13.417,0.075,14.759,0.224,15.274,0.335
46,62,13.394,0.111,0,0.619770,13.072,0.131,13.064,0.094,13.200,0.234,12.856,0.040,14.518,0.312,14.967,0.453
47,63,13.203,0.078,0,0.825943,12.834,0.055,12.832,0.079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,64,13.662,0.071,1,0.344497,13.429,0.061,13.389,0.029,NaN,NaN,NaN,NaN,14.569,0.178,14.927,0.244
49,66,13.552,0.062,1,0.407266,13.328,0.063,13.260,0.026,NaN,NaN,NaN,NaN,14.496,0.127,14.875,0.194
50,67,13.619,0.137,0,0.564451,13.377,0.072,13.301,0.079,NaN,NaN,NaN,NaN,14.719,0.296,NaN,NaN
51,68,13.233,0.054,1,0.534609,13.002,0.075,12.973,0.035,NaN,NaN,NaN,NaN,14.247,0.122,14.680,0.183
52,69,NaN,NaN,0,0.635221,NaN,NaN,13.067,0.056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,70,13.517,0.055,1,0.390687,13.297,0.043,13.254,0.020,NaN,NaN,NaN,NaN,14.566,0.149,14.942,0.157
54,71,13.604,0.076,1,0.357544,13.331,0.045,13.354,0.041,13.502,0.081,13.106,0.098,14.544,0.159,14.923,0.223
55,72,13.542,0.066,1,0.384522,13.307,0.053,13.292,0.044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,73,13.522,0.128,0,0.575215,13.245,0.104,13.216,0.070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,74,13.626,0.125,0,0.503209,13.484,0.154,13.322,0.092,NaN,NaN,NaN,NaN,14.686,0.347,15.057,0.508
58,75,13.413,0.065,1,0.422174,13.181,0.061,13.146,0.041,NaN,NaN,NaN,NaN,14.484,0.139,14.864,0.191
59,76,13.654,0.062,1,0.337962,13.508,0.091,13.439,0.028,NaN,NaN,NaN,NaN,14.523,0.135,14.870,0.195
,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...